version: "3"
services:
  redis:
    restart: always
    build: ./redis
    ports:
      - 6379:6379
  go:
    build: ../
    depends_on: 
      - redis
    env_file: test.env
    ports:
      - 80:80
      - 53:53/udp