name: main

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
    - name: Install
      run: go get -u golang.org/x/lint/golint
    - name: Lint
      run: /home/runner/go/bin/golint -set_exit_status main